### ISSUE TITLE
Theming ShadcnUI

### ISSUE THREAD

**Issue by musiur** [crescents-stack/laundry-care#24]

**Comment by parag477** [comment]
I want to work on this issue. Can you assign me this

**Comment by musiur** [comment]
Sure!

**Comment by musiur** [comment]
We will have 4 major colors. These colors will be used as primary color for four different themes.



![Image](https://github.com/crescents-stack/laundry-care/assets/99522246/6e238933-45ed-4f64-bc40-c29ee385539c)

Here is the [Figma](https://www.figma.com/file/IZZxLNSQfoaqeYOKTDFg7y/LaundryCare?type=design&node-id=6%3A13&mode=design&t=YD9FSKDef1BAHOcu-1)

We can view all the colors there!

**Comment by musiur** [comment]
@parag477 Brother is there any update!

**Comment by musiur** [comment]
Fixes: #24

ShadcnUI Allow Us only to mode: Light | Dark ~ System

Hence, We have implemented Four theme using the Plain CSS color theme concept and TailwindCSS inline styling Feature!
