### ISSUE TITLE
[Feature] Remember me in Login

### ISSUE THREAD

**Issue by musiur** [crescents-stack/laundry-care#47]
![Image](https://github.com/crescents-stack/laundry-care/assets/99522246/11f09f07-4c94-46b2-8687-f9402c652788)

**Comment by sahith29s** [comment]
Should I do with json web tokens?

**Comment by musiur** [comment]
No, You will need to use the localStorage or sessionStorage in Login pages.
 At first render in that perticular page you will have to check whether the credentials are already found in (local or session storage) or not. 
If found than using an useEffect hook with empty dependency array you have to update the formData state.
Else do nothing!

Again, If any user tries to use remember me than you will have to add that in the localStorage or sessionStorage for future usage.

😄

**Comment by musiur** [comment]
You may try to understand this code at first:[ login.tsx](https://github.com/crescents-stack/laundry-care/blob/main/src/app/%5Blang%5D/user/auth/login/page.tsx)

Still, if there is any issue to understand then just wait a bit to be implemented by me and then you can copy to other pages.

**Comment by musiur** [comment]
Let me fix this issue. Then you may try for other login pages 😄

**Comment by musiur** [comment]
@sahith29s You may contribute to other login pages!

Fixes #47
